name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main, release/*, bugfix/* ]
  pull_request:
    branches: [ main, release/*, bugfix/* ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'CODEOWNERS'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  CodeQL:
    uses: eclipse-edc/.github/.github/workflows/codeql-analysis.yml@main
    secrets: inherit

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Build
        run: ./gradlew build
